[build]
  command = "npm install && npm run build"
  publish = "."
  functions = "functions"

[[headers]]
  for = "/feed.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[plugins]]
  package = "@netlify/plugin-scheduled"

[functions."scheduled-update"]
  schedule = "@hourly"