[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "."

[[headers]]
  for = "/feed.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[plugins]]
  package = "@netlify/plugin-schedule"

  [plugins.inputs]
  schedule = "@hourly"